on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

env:
  # Setting an environment variable with the value of a configuration variable
  package_folder: packages/${{ inputs.package }}

jobs:
  # we need to prepend _ to conform to 1155 standards
  coverage:
    uses: ./.github/workflows/coverage.yml
    with:
      package: ${{ inputs.package }}
