name: "Foundry"

on: "push"

env:
  # Setting an environment variable with the value of a configuration variable
  $build_artifact: foundry_artifact

jobs:
  build:
    name: Build and cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Build contracts
        run: |
          npx turbo run build:contracts

      - name: Archive built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: $build_artifact
          path: |
            **/*/cache
            **/*/out
          retention-days: 1

  contract_size_check:
    needs: build
    strategy:
      fail-fast: true

    name: Contract Size Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Download foundry artifacts
        uses: actions/download-artifact@v3
        with:
          name: $build_artifact

      - name: Check contract sizes
        run: |
          npx turbo run check-contract-size

  test:
    needs: build
    strategy:
      fail-fast: true

    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Download foundry artifacts
        uses: actions/download-artifact@v3
        with:
          name: $build_artifact

      - name: Run tests
        run: |
          npx turbo run test

  test_fork:
    needs: build
    strategy:
      fail-fast: true

    name: Fork Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Download foundry artifacts
        uses: actions/download-artifact@v3
        with:
          name: $build_artifact

      - name: Run fork tests
        run: |
          npx turbo run test:fork
        env:
          FORK_TEST_CHAINS: mainnet,goerli,optimism,optimism_goerli,zora,zora_goerli,base_goerli,base
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}

  storage_layout:
    needs: build
    strategy:
      fail-fast: true

    name: Inpect storage layout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Download foundry artifacts
        uses: actions/download-artifact@v3
        with:
          name: $build_artifact

      - name: "Inspect Storage Layout"
        continue-on-error: false
        run: npx turbo run storage-inspect:check

  build_js:
    needs: build
    strategy:
      fail-fast: true

    name: Build JS Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Download foundry artifacts
        uses: actions/download-artifact@v3
        with:
          name: $build_artifact

      - name: Build js package
        run: |
          npx turbo run prepack

  coverage-1155:
    uses: ./.github/workflows/coverage.yml
    with:
      package: "1155-contracts"

  coverage-protocol-rewards:
    uses: ./.github/workflows/coverage.yml
    with:
      package: "protocol-rewards"
